### PR TITLE
Extend epy_spectrum.py to global non-stretched Gaussian grids

### PR DESCRIPTION
**Pull request by MayeulDestouchesMF**
## Description

This PR proposes an extension of epy_spectrum.py to global non-stretched Gaussian grids. The spectral coefficients are just read from the field data, and aggregated by total wavenumber, similarly to what is done in the `SPNORM` routines of arpifs. 

This extension relies on the addition of a new function `epygram.spectra.global_variances(field: H2DField)`, for use outside of epy_spectrum.py. 

A new function `prepare_field_and_get_spectrum` has been introduced in epy_plot.py to limit duplicate code.

## Impact

This should have no impact on existing use. The code has been refactored to have different behaviour depending on the geometry, the current behaviour for LAM fields is unchanged.

### CODE REVIEW

**Comment by AlexandreMary** [comment]
Hi Mayeul, thanks for that.
Only comment: the function `prepare_field_and_get_spectrum`, I find it a bit odd that it takes a `compute_spectrum` argument and potentially returns nothing.
I know things are a bit weird with `diffonly` parts, but I would rather split it into 2 functions, one `prepare_field` and one `get_spectrum`.

Or even better: implement a `H2DField.spectrum()` method which systematically does the sp2gp/gp2sp transform according to geometry (with an optional spectral_geometry argument for the gp2sp case) and then calls the appropriate function from `epygram.spectra`.
And in `epy_spectrum.py` you would only call this `field.spectrum(...)`

**Comment by MayeulDestouchesMF** [comment]
What you suggests sounds much cleaner, thank you! I am working on it.

**Comment by MayeulDestouchesMF** [comment]
@AlexandreMary, here is a revised proposal. 

I guess this could be improved, for instance by removing the `fname` parameter of `H2DField.spectrum()`.  I don't know if there is a generic way to get the field name from the field (such as `field.fid["FA"]` for FA files).

**Comment by AlexandreMary** [comment]
OK good for me now. I will merge

**Pull request merged**
